### ISSUE TITLE
GMMSP source code.

### ISSUE THREAD

**Issue by cbalint13** [ahban/GMMSP#1]
Dear Zhihua Ban,

* Are there any plans to release source code for the demonstrator ?

**Comment by ahban** [comment]
@cbalint13 
Yes. I will upload the code to this repository. I am still working on this code :(.  I am really happy if it will help you.  For now, i just put the compiled mex file. If you need any help to run the demo, please let me know.

**Comment by ahban** [comment]
the source code has been released long time ago. I close this issue for now.
